apiVersion: 3
dataDisplay:
  textFormats:
    layout-orig-full: 
      method: layoutRich
      style:  normal
interfaceDefaults: {}
provenanceSpec:
  corpus: Samaritan Pentateuch - Genesis
  version: '0.2'
writing: hbo
typeDisplay:
  verse:
    label: '{verse}'
    template: '{verse}'
    verselike: true
  word:
    features: lex
  sign:
    features: sign
